# Move Direction
bool stop
bool walking_front
bool walking_back
bool rotating_left
bool rotating_right

# Robot Mode Flag
bool wheel_control_mode_1
bool wheel_control_mode_2
bool wheel_control_mode_3
bool wheel_brake_mode
bool wheel_release_mode
bool go_to_dock
bool dock_escape

# charge
bool do_not_charge
bool charging
bool charge_finish
bool fault_in_charge

# Button
bool stop_btn_hit
bool sleep_btn_hit




