// Generated by gencpp from file BaseNode/GetObstacleDistance.msg
// DO NOT EDIT!


#ifndef BASENODE_MESSAGE_GETOBSTACLEDISTANCE_H
#define BASENODE_MESSAGE_GETOBSTACLEDISTANCE_H

#include <ros/service_traits.h>


#include <BaseNode/GetObstacleDistanceRequest.h>
#include <BaseNode/GetObstacleDistanceResponse.h>


namespace BaseNode
{

struct GetObstacleDistance
{

typedef GetObstacleDistanceRequest Request;
typedef GetObstacleDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetObstacleDistance
} // namespace BaseNode


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::BaseNode::GetObstacleDistance > {
  static const char* value()
  {
    return "01f181dd22773f5f5fa03ae27cc740e5";
  }

  static const char* value(const ::BaseNode::GetObstacleDistance&) { return value(); }
};

template<>
struct DataType< ::BaseNode::GetObstacleDistance > {
  static const char* value()
  {
    return "BaseNode/GetObstacleDistance";
  }

  static const char* value(const ::BaseNode::GetObstacleDistance&) { return value(); }
};


// service_traits::MD5Sum< ::BaseNode::GetObstacleDistanceRequest> should match 
// service_traits::MD5Sum< ::BaseNode::GetObstacleDistance > 
template<>
struct MD5Sum< ::BaseNode::GetObstacleDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::BaseNode::GetObstacleDistance >::value();
  }
  static const char* value(const ::BaseNode::GetObstacleDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::BaseNode::GetObstacleDistanceRequest> should match 
// service_traits::DataType< ::BaseNode::GetObstacleDistance > 
template<>
struct DataType< ::BaseNode::GetObstacleDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::BaseNode::GetObstacleDistance >::value();
  }
  static const char* value(const ::BaseNode::GetObstacleDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::BaseNode::GetObstacleDistanceResponse> should match 
// service_traits::MD5Sum< ::BaseNode::GetObstacleDistance > 
template<>
struct MD5Sum< ::BaseNode::GetObstacleDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::BaseNode::GetObstacleDistance >::value();
  }
  static const char* value(const ::BaseNode::GetObstacleDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::BaseNode::GetObstacleDistanceResponse> should match 
// service_traits::DataType< ::BaseNode::GetObstacleDistance > 
template<>
struct DataType< ::BaseNode::GetObstacleDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::BaseNode::GetObstacleDistance >::value();
  }
  static const char* value(const ::BaseNode::GetObstacleDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASENODE_MESSAGE_GETOBSTACLEDISTANCE_H
