// Generated by gencpp from file BaseNode/IMUReport.msg
// DO NOT EDIT!


#ifndef BASENODE_MESSAGE_IMUREPORT_H
#define BASENODE_MESSAGE_IMUREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace BaseNode
{
template <class ContainerAllocator>
struct IMUReport_
{
  typedef IMUReport_<ContainerAllocator> Type;

  IMUReport_()
    : linear_acc()
    , angular_acc()  {
    }
  IMUReport_(const ContainerAllocator& _alloc)
    : linear_acc(_alloc)
    , angular_acc(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acc_type;
  _linear_acc_type linear_acc;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_acc_type;
  _angular_acc_type angular_acc;





  typedef boost::shared_ptr< ::BaseNode::IMUReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::BaseNode::IMUReport_<ContainerAllocator> const> ConstPtr;

}; // struct IMUReport_

typedef ::BaseNode::IMUReport_<std::allocator<void> > IMUReport;

typedef boost::shared_ptr< ::BaseNode::IMUReport > IMUReportPtr;
typedef boost::shared_ptr< ::BaseNode::IMUReport const> IMUReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::BaseNode::IMUReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::BaseNode::IMUReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace BaseNode

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'BaseNode': ['/home/c01/naya_navigation/src/BaseNode/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::IMUReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::IMUReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::IMUReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::IMUReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::IMUReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::IMUReport_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::BaseNode::IMUReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fa1cce6f2c843c4ab29f13782961f52";
  }

  static const char* value(const ::BaseNode::IMUReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fa1cce6f2c843c4ULL;
  static const uint64_t static_value2 = 0xab29f13782961f52ULL;
};

template<class ContainerAllocator>
struct DataType< ::BaseNode::IMUReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BaseNode/IMUReport";
  }

  static const char* value(const ::BaseNode::IMUReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::BaseNode::IMUReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 linear_acc\n\
geometry_msgs/Vector3 angular_acc\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::BaseNode::IMUReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::BaseNode::IMUReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_acc);
      stream.next(m.angular_acc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IMUReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::BaseNode::IMUReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::BaseNode::IMUReport_<ContainerAllocator>& v)
  {
    s << indent << "linear_acc: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acc);
    s << indent << "angular_acc: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_acc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASENODE_MESSAGE_IMUREPORT_H
