// Generated by gencpp from file BaseNode/LEDReportResponse.msg
// DO NOT EDIT!


#ifndef BASENODE_MESSAGE_LEDREPORTRESPONSE_H
#define BASENODE_MESSAGE_LEDREPORTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace BaseNode
{
template <class ContainerAllocator>
struct LEDReportResponse_
{
  typedef LEDReportResponse_<ContainerAllocator> Type;

  LEDReportResponse_()
    : red_led(0)
    , green_led(0)
    , blue_led(0)
    , left_dig_led(false)
    , right_dig_led(false)  {
    }
  LEDReportResponse_(const ContainerAllocator& _alloc)
    : red_led(0)
    , green_led(0)
    , blue_led(0)
    , left_dig_led(false)
    , right_dig_led(false)  {
  (void)_alloc;
    }



   typedef uint8_t _red_led_type;
  _red_led_type red_led;

   typedef uint8_t _green_led_type;
  _green_led_type green_led;

   typedef uint8_t _blue_led_type;
  _blue_led_type blue_led;

   typedef uint8_t _left_dig_led_type;
  _left_dig_led_type left_dig_led;

   typedef uint8_t _right_dig_led_type;
  _right_dig_led_type right_dig_led;





  typedef boost::shared_ptr< ::BaseNode::LEDReportResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::BaseNode::LEDReportResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LEDReportResponse_

typedef ::BaseNode::LEDReportResponse_<std::allocator<void> > LEDReportResponse;

typedef boost::shared_ptr< ::BaseNode::LEDReportResponse > LEDReportResponsePtr;
typedef boost::shared_ptr< ::BaseNode::LEDReportResponse const> LEDReportResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::BaseNode::LEDReportResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::BaseNode::LEDReportResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace BaseNode

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'BaseNode': ['/home/c01/naya_navigation/src/BaseNode/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::LEDReportResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::LEDReportResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::LEDReportResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::LEDReportResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::LEDReportResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::LEDReportResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::BaseNode::LEDReportResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2378127639e4cdf5ca0794bcb9a9083";
  }

  static const char* value(const ::BaseNode::LEDReportResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2378127639e4cdfULL;
  static const uint64_t static_value2 = 0x5ca0794bcb9a9083ULL;
};

template<class ContainerAllocator>
struct DataType< ::BaseNode::LEDReportResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BaseNode/LEDReportResponse";
  }

  static const char* value(const ::BaseNode::LEDReportResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::BaseNode::LEDReportResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 red_led\n\
uint8 green_led\n\
uint8 blue_led\n\
bool left_dig_led\n\
bool right_dig_led\n\
\n\
";
  }

  static const char* value(const ::BaseNode::LEDReportResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::BaseNode::LEDReportResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.red_led);
      stream.next(m.green_led);
      stream.next(m.blue_led);
      stream.next(m.left_dig_led);
      stream.next(m.right_dig_led);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LEDReportResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::BaseNode::LEDReportResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::BaseNode::LEDReportResponse_<ContainerAllocator>& v)
  {
    s << indent << "red_led: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.red_led);
    s << indent << "green_led: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.green_led);
    s << indent << "blue_led: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blue_led);
    s << indent << "left_dig_led: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_dig_led);
    s << indent << "right_dig_led: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_dig_led);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASENODE_MESSAGE_LEDREPORTRESPONSE_H
