// Generated by gencpp from file BaseNode/MagnetReport.msg
// DO NOT EDIT!


#ifndef BASENODE_MESSAGE_MAGNETREPORT_H
#define BASENODE_MESSAGE_MAGNETREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace BaseNode
{
template <class ContainerAllocator>
struct MagnetReport_
{
  typedef MagnetReport_<ContainerAllocator> Type;

  MagnetReport_()
    : cell()  {
    }
  MagnetReport_(const ContainerAllocator& _alloc)
    : cell(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _cell_type;
  _cell_type cell;





  typedef boost::shared_ptr< ::BaseNode::MagnetReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::BaseNode::MagnetReport_<ContainerAllocator> const> ConstPtr;

}; // struct MagnetReport_

typedef ::BaseNode::MagnetReport_<std::allocator<void> > MagnetReport;

typedef boost::shared_ptr< ::BaseNode::MagnetReport > MagnetReportPtr;
typedef boost::shared_ptr< ::BaseNode::MagnetReport const> MagnetReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::BaseNode::MagnetReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::BaseNode::MagnetReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace BaseNode

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'BaseNode': ['/home/c01/naya_navigation/src/BaseNode/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::MagnetReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::MagnetReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::MagnetReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::MagnetReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::MagnetReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::MagnetReport_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::BaseNode::MagnetReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9f73b0509699f216ff940c7a6e46e63";
  }

  static const char* value(const ::BaseNode::MagnetReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9f73b0509699f21ULL;
  static const uint64_t static_value2 = 0x6ff940c7a6e46e63ULL;
};

template<class ContainerAllocator>
struct DataType< ::BaseNode::MagnetReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BaseNode/MagnetReport";
  }

  static const char* value(const ::BaseNode::MagnetReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::BaseNode::MagnetReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] cell\n\
";
  }

  static const char* value(const ::BaseNode::MagnetReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::BaseNode::MagnetReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cell);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagnetReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::BaseNode::MagnetReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::BaseNode::MagnetReport_<ContainerAllocator>& v)
  {
    s << indent << "cell[]" << std::endl;
    for (size_t i = 0; i < v.cell.size(); ++i)
    {
      s << indent << "  cell[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.cell[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASENODE_MESSAGE_MAGNETREPORT_H
