// Generated by gencpp from file BaseNode/RealSpeedData.msg
// DO NOT EDIT!


#ifndef BASENODE_MESSAGE_REALSPEEDDATA_H
#define BASENODE_MESSAGE_REALSPEEDDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace BaseNode
{
template <class ContainerAllocator>
struct RealSpeedData_
{
  typedef RealSpeedData_<ContainerAllocator> Type;

  RealSpeedData_()
    : left_control_value(0.0)
    , left_error_value(0.0)
    , left_reference_speed_value(0.0)
    , left_real_speed_value(0.0)
    , left_output_PWM_value(0.0)
    , left_brake_value(0.0)
    , right_control_value(0.0)
    , right_error_value(0.0)
    , right_reference_speed_value(0.0)
    , right_real_speed_value(0.0)
    , right_output_PWM_value(0.0)
    , right_brake_value(0.0)  {
    }
  RealSpeedData_(const ContainerAllocator& _alloc)
    : left_control_value(0.0)
    , left_error_value(0.0)
    , left_reference_speed_value(0.0)
    , left_real_speed_value(0.0)
    , left_output_PWM_value(0.0)
    , left_brake_value(0.0)
    , right_control_value(0.0)
    , right_error_value(0.0)
    , right_reference_speed_value(0.0)
    , right_real_speed_value(0.0)
    , right_output_PWM_value(0.0)
    , right_brake_value(0.0)  {
  (void)_alloc;
    }



   typedef float _left_control_value_type;
  _left_control_value_type left_control_value;

   typedef float _left_error_value_type;
  _left_error_value_type left_error_value;

   typedef float _left_reference_speed_value_type;
  _left_reference_speed_value_type left_reference_speed_value;

   typedef float _left_real_speed_value_type;
  _left_real_speed_value_type left_real_speed_value;

   typedef float _left_output_PWM_value_type;
  _left_output_PWM_value_type left_output_PWM_value;

   typedef float _left_brake_value_type;
  _left_brake_value_type left_brake_value;

   typedef float _right_control_value_type;
  _right_control_value_type right_control_value;

   typedef float _right_error_value_type;
  _right_error_value_type right_error_value;

   typedef float _right_reference_speed_value_type;
  _right_reference_speed_value_type right_reference_speed_value;

   typedef float _right_real_speed_value_type;
  _right_real_speed_value_type right_real_speed_value;

   typedef float _right_output_PWM_value_type;
  _right_output_PWM_value_type right_output_PWM_value;

   typedef float _right_brake_value_type;
  _right_brake_value_type right_brake_value;





  typedef boost::shared_ptr< ::BaseNode::RealSpeedData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::BaseNode::RealSpeedData_<ContainerAllocator> const> ConstPtr;

}; // struct RealSpeedData_

typedef ::BaseNode::RealSpeedData_<std::allocator<void> > RealSpeedData;

typedef boost::shared_ptr< ::BaseNode::RealSpeedData > RealSpeedDataPtr;
typedef boost::shared_ptr< ::BaseNode::RealSpeedData const> RealSpeedDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::BaseNode::RealSpeedData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::BaseNode::RealSpeedData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace BaseNode

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'BaseNode': ['/home/c01/naya_navigation/src/BaseNode/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::RealSpeedData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::RealSpeedData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::RealSpeedData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::RealSpeedData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::RealSpeedData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::RealSpeedData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::BaseNode::RealSpeedData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af4042522846a38590d01848f45d1cda";
  }

  static const char* value(const ::BaseNode::RealSpeedData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf4042522846a385ULL;
  static const uint64_t static_value2 = 0x90d01848f45d1cdaULL;
};

template<class ContainerAllocator>
struct DataType< ::BaseNode::RealSpeedData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BaseNode/RealSpeedData";
  }

  static const char* value(const ::BaseNode::RealSpeedData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::BaseNode::RealSpeedData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left_control_value\n\
float32 left_error_value\n\
float32 left_reference_speed_value\n\
float32 left_real_speed_value\n\
float32 left_output_PWM_value\n\
float32 left_brake_value\n\
float32 right_control_value\n\
float32 right_error_value\n\
float32 right_reference_speed_value\n\
float32 right_real_speed_value\n\
float32 right_output_PWM_value\n\
float32 right_brake_value\n\
";
  }

  static const char* value(const ::BaseNode::RealSpeedData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::BaseNode::RealSpeedData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_control_value);
      stream.next(m.left_error_value);
      stream.next(m.left_reference_speed_value);
      stream.next(m.left_real_speed_value);
      stream.next(m.left_output_PWM_value);
      stream.next(m.left_brake_value);
      stream.next(m.right_control_value);
      stream.next(m.right_error_value);
      stream.next(m.right_reference_speed_value);
      stream.next(m.right_real_speed_value);
      stream.next(m.right_output_PWM_value);
      stream.next(m.right_brake_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RealSpeedData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::BaseNode::RealSpeedData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::BaseNode::RealSpeedData_<ContainerAllocator>& v)
  {
    s << indent << "left_control_value: ";
    Printer<float>::stream(s, indent + "  ", v.left_control_value);
    s << indent << "left_error_value: ";
    Printer<float>::stream(s, indent + "  ", v.left_error_value);
    s << indent << "left_reference_speed_value: ";
    Printer<float>::stream(s, indent + "  ", v.left_reference_speed_value);
    s << indent << "left_real_speed_value: ";
    Printer<float>::stream(s, indent + "  ", v.left_real_speed_value);
    s << indent << "left_output_PWM_value: ";
    Printer<float>::stream(s, indent + "  ", v.left_output_PWM_value);
    s << indent << "left_brake_value: ";
    Printer<float>::stream(s, indent + "  ", v.left_brake_value);
    s << indent << "right_control_value: ";
    Printer<float>::stream(s, indent + "  ", v.right_control_value);
    s << indent << "right_error_value: ";
    Printer<float>::stream(s, indent + "  ", v.right_error_value);
    s << indent << "right_reference_speed_value: ";
    Printer<float>::stream(s, indent + "  ", v.right_reference_speed_value);
    s << indent << "right_real_speed_value: ";
    Printer<float>::stream(s, indent + "  ", v.right_real_speed_value);
    s << indent << "right_output_PWM_value: ";
    Printer<float>::stream(s, indent + "  ", v.right_output_PWM_value);
    s << indent << "right_brake_value: ";
    Printer<float>::stream(s, indent + "  ", v.right_brake_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASENODE_MESSAGE_REALSPEEDDATA_H
