// Generated by gencpp from file BaseNode/RFIDReport.msg
// DO NOT EDIT!


#ifndef BASENODE_MESSAGE_RFIDREPORT_H
#define BASENODE_MESSAGE_RFIDREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace BaseNode
{
template <class ContainerAllocator>
struct RFIDReport_
{
  typedef RFIDReport_<ContainerAllocator> Type;

  RFIDReport_()
    : RFIDNo()
    , detect_status(false)  {
    }
  RFIDReport_(const ContainerAllocator& _alloc)
    : RFIDNo(_alloc)
    , detect_status(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _RFIDNo_type;
  _RFIDNo_type RFIDNo;

   typedef uint8_t _detect_status_type;
  _detect_status_type detect_status;





  typedef boost::shared_ptr< ::BaseNode::RFIDReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::BaseNode::RFIDReport_<ContainerAllocator> const> ConstPtr;

}; // struct RFIDReport_

typedef ::BaseNode::RFIDReport_<std::allocator<void> > RFIDReport;

typedef boost::shared_ptr< ::BaseNode::RFIDReport > RFIDReportPtr;
typedef boost::shared_ptr< ::BaseNode::RFIDReport const> RFIDReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::BaseNode::RFIDReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::BaseNode::RFIDReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace BaseNode

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'BaseNode': ['/home/c01/naya_navigation/src/BaseNode/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::RFIDReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::RFIDReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::RFIDReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::RFIDReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::RFIDReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::RFIDReport_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::BaseNode::RFIDReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f5274ec60f335c39997a38a6d19ff0d";
  }

  static const char* value(const ::BaseNode::RFIDReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f5274ec60f335c3ULL;
  static const uint64_t static_value2 = 0x9997a38a6d19ff0dULL;
};

template<class ContainerAllocator>
struct DataType< ::BaseNode::RFIDReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BaseNode/RFIDReport";
  }

  static const char* value(const ::BaseNode::RFIDReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::BaseNode::RFIDReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string RFIDNo\n\
bool detect_status\n\
";
  }

  static const char* value(const ::BaseNode::RFIDReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::BaseNode::RFIDReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.RFIDNo);
      stream.next(m.detect_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RFIDReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::BaseNode::RFIDReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::BaseNode::RFIDReport_<ContainerAllocator>& v)
  {
    s << indent << "RFIDNo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.RFIDNo);
    s << indent << "detect_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detect_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASENODE_MESSAGE_RFIDREPORT_H
