// Generated by gencpp from file BaseNode/SetObstacleDistance.msg
// DO NOT EDIT!


#ifndef BASENODE_MESSAGE_SETOBSTACLEDISTANCE_H
#define BASENODE_MESSAGE_SETOBSTACLEDISTANCE_H

#include <ros/service_traits.h>


#include <BaseNode/SetObstacleDistanceRequest.h>
#include <BaseNode/SetObstacleDistanceResponse.h>


namespace BaseNode
{

struct SetObstacleDistance
{

typedef SetObstacleDistanceRequest Request;
typedef SetObstacleDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetObstacleDistance
} // namespace BaseNode


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::BaseNode::SetObstacleDistance > {
  static const char* value()
  {
    return "744c1032f68198df9c2b4b2ede38d155";
  }

  static const char* value(const ::BaseNode::SetObstacleDistance&) { return value(); }
};

template<>
struct DataType< ::BaseNode::SetObstacleDistance > {
  static const char* value()
  {
    return "BaseNode/SetObstacleDistance";
  }

  static const char* value(const ::BaseNode::SetObstacleDistance&) { return value(); }
};


// service_traits::MD5Sum< ::BaseNode::SetObstacleDistanceRequest> should match 
// service_traits::MD5Sum< ::BaseNode::SetObstacleDistance > 
template<>
struct MD5Sum< ::BaseNode::SetObstacleDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::BaseNode::SetObstacleDistance >::value();
  }
  static const char* value(const ::BaseNode::SetObstacleDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::BaseNode::SetObstacleDistanceRequest> should match 
// service_traits::DataType< ::BaseNode::SetObstacleDistance > 
template<>
struct DataType< ::BaseNode::SetObstacleDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::BaseNode::SetObstacleDistance >::value();
  }
  static const char* value(const ::BaseNode::SetObstacleDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::BaseNode::SetObstacleDistanceResponse> should match 
// service_traits::MD5Sum< ::BaseNode::SetObstacleDistance > 
template<>
struct MD5Sum< ::BaseNode::SetObstacleDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::BaseNode::SetObstacleDistance >::value();
  }
  static const char* value(const ::BaseNode::SetObstacleDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::BaseNode::SetObstacleDistanceResponse> should match 
// service_traits::DataType< ::BaseNode::SetObstacleDistance > 
template<>
struct DataType< ::BaseNode::SetObstacleDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::BaseNode::SetObstacleDistance >::value();
  }
  static const char* value(const ::BaseNode::SetObstacleDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASENODE_MESSAGE_SETOBSTACLEDISTANCE_H
