// Generated by gencpp from file BaseNode/SonicReport.msg
// DO NOT EDIT!


#ifndef BASENODE_MESSAGE_SONICREPORT_H
#define BASENODE_MESSAGE_SONICREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace BaseNode
{
template <class ContainerAllocator>
struct SonicReport_
{
  typedef SonicReport_<ContainerAllocator> Type;

  SonicReport_()
    : sonic_too_close()  {
    }
  SonicReport_(const ContainerAllocator& _alloc)
    : sonic_too_close(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _sonic_too_close_type;
  _sonic_too_close_type sonic_too_close;





  typedef boost::shared_ptr< ::BaseNode::SonicReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::BaseNode::SonicReport_<ContainerAllocator> const> ConstPtr;

}; // struct SonicReport_

typedef ::BaseNode::SonicReport_<std::allocator<void> > SonicReport;

typedef boost::shared_ptr< ::BaseNode::SonicReport > SonicReportPtr;
typedef boost::shared_ptr< ::BaseNode::SonicReport const> SonicReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::BaseNode::SonicReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::BaseNode::SonicReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace BaseNode

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'BaseNode': ['/home/c01/naya_navigation/src/BaseNode/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::SonicReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::BaseNode::SonicReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::SonicReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BaseNode::SonicReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::SonicReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BaseNode::SonicReport_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::BaseNode::SonicReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e85b346da5a184206999e10ccebec12";
  }

  static const char* value(const ::BaseNode::SonicReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e85b346da5a1842ULL;
  static const uint64_t static_value2 = 0x06999e10ccebec12ULL;
};

template<class ContainerAllocator>
struct DataType< ::BaseNode::SonicReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BaseNode/SonicReport";
  }

  static const char* value(const ::BaseNode::SonicReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::BaseNode::SonicReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] sonic_too_close\n\
";
  }

  static const char* value(const ::BaseNode::SonicReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::BaseNode::SonicReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sonic_too_close);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SonicReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::BaseNode::SonicReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::BaseNode::SonicReport_<ContainerAllocator>& v)
  {
    s << indent << "sonic_too_close[]" << std::endl;
    for (size_t i = 0; i < v.sonic_too_close.size(); ++i)
    {
      s << indent << "  sonic_too_close[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.sonic_too_close[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASENODE_MESSAGE_SONICREPORT_H
