(cl:defpackage BaseNode-srv
  (:use )
  (:export
   "GETOBSTACLEDISTANCE"
   "<GETOBSTACLEDISTANCE-REQUEST>"
   "GETOBSTACLEDISTANCE-REQUEST"
   "<GETOBSTACLEDISTANCE-RESPONSE>"
   "GETOBSTACLEDISTANCE-RESPONSE"
   "LEDREPORT"
   "<LEDREPORT-REQUEST>"
   "LEDREPORT-REQUEST"
   "<LEDREPORT-RESPONSE>"
   "LEDREPORT-RESPONSE"
   "SETOBSTACLEDISTANCE"
   "<SETOBSTACLEDISTANCE-REQUEST>"
   "SETOBSTACLEDISTANCE-REQUEST"
   "<SETOBSTACLEDISTANCE-RESPONSE>"
   "SETOBSTACLEDISTANCE-RESPONSE"
  ))

