# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from BaseNode/DigitLEDControl.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DigitLEDControl(genpy.Message):
  _md5sum = "5fcb3983ee7f931b51ef2d1803e3ef6a"
  _type = "BaseNode/DigitLEDControl"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool left_dig_led
bool right_dig_led
float32 left_run_time
float32 right_run_time
"""
  __slots__ = ['left_dig_led','right_dig_led','left_run_time','right_run_time']
  _slot_types = ['bool','bool','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_dig_led,right_dig_led,left_run_time,right_run_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DigitLEDControl, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_dig_led is None:
        self.left_dig_led = False
      if self.right_dig_led is None:
        self.right_dig_led = False
      if self.left_run_time is None:
        self.left_run_time = 0.
      if self.right_run_time is None:
        self.right_run_time = 0.
    else:
      self.left_dig_led = False
      self.right_dig_led = False
      self.left_run_time = 0.
      self.right_run_time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2f().pack(_x.left_dig_led, _x.right_dig_led, _x.left_run_time, _x.right_run_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.left_dig_led, _x.right_dig_led, _x.left_run_time, _x.right_run_time,) = _get_struct_2B2f().unpack(str[start:end])
      self.left_dig_led = bool(self.left_dig_led)
      self.right_dig_led = bool(self.right_dig_led)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2f().pack(_x.left_dig_led, _x.right_dig_led, _x.left_run_time, _x.right_run_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.left_dig_led, _x.right_dig_led, _x.left_run_time, _x.right_run_time,) = _get_struct_2B2f().unpack(str[start:end])
      self.left_dig_led = bool(self.left_dig_led)
      self.right_dig_led = bool(self.right_dig_led)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2f = None
def _get_struct_2B2f():
    global _struct_2B2f
    if _struct_2B2f is None:
        _struct_2B2f = struct.Struct("<2B2f")
    return _struct_2B2f
