// Generated by gencpp from file simple_navigation_goals/auto_info.msg
// DO NOT EDIT!


#ifndef SIMPLE_NAVIGATION_GOALS_MESSAGE_AUTO_INFO_H
#define SIMPLE_NAVIGATION_GOALS_MESSAGE_AUTO_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_navigation_goals
{
template <class ContainerAllocator>
struct auto_info_
{
  typedef auto_info_<ContainerAllocator> Type;

  auto_info_()
    : info(false)  {
    }
  auto_info_(const ContainerAllocator& _alloc)
    : info(false)  {
  (void)_alloc;
    }



   typedef uint8_t _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::simple_navigation_goals::auto_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_navigation_goals::auto_info_<ContainerAllocator> const> ConstPtr;

}; // struct auto_info_

typedef ::simple_navigation_goals::auto_info_<std::allocator<void> > auto_info;

typedef boost::shared_ptr< ::simple_navigation_goals::auto_info > auto_infoPtr;
typedef boost::shared_ptr< ::simple_navigation_goals::auto_info const> auto_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_navigation_goals::auto_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_navigation_goals::auto_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_navigation_goals

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'simple_navigation_goals': ['/home/c01/naya_navigation/src/simple_navigation_goals/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_navigation_goals::auto_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_navigation_goals::auto_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_navigation_goals::auto_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_navigation_goals::auto_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_navigation_goals::auto_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_navigation_goals::auto_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_navigation_goals::auto_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65d497f9cf95d78ecfe2d84e8a1a7ad3";
  }

  static const char* value(const ::simple_navigation_goals::auto_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65d497f9cf95d78eULL;
  static const uint64_t static_value2 = 0xcfe2d84e8a1a7ad3ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_navigation_goals::auto_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_navigation_goals/auto_info";
  }

  static const char* value(const ::simple_navigation_goals::auto_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_navigation_goals::auto_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool info\n\
";
  }

  static const char* value(const ::simple_navigation_goals::auto_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_navigation_goals::auto_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct auto_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_navigation_goals::auto_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_navigation_goals::auto_info_<ContainerAllocator>& v)
  {
    s << indent << "info: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_NAVIGATION_GOALS_MESSAGE_AUTO_INFO_H
