(cl:in-package BaseNode-msg)
(cl:export '(STOP-VAL
          STOP
          WALKING_FRONT-VAL
          WALKING_FRONT
          WALKING_BACK-VAL
          WALKING_BACK
          ROTATING_LEFT-VAL
          ROTATING_LEFT
          ROTATING_RIGHT-VAL
          ROTATING_RIGHT
          WHEEL_CONTROL_MODE_1-VAL
          WHEEL_CONTROL_MODE_1
          WHEEL_CONTROL_MODE_2-VAL
          WHEEL_CONTROL_MODE_2
          WHEEL_CONTROL_MODE_3-VAL
          WHEEL_CONTROL_MODE_3
          WHEEL_BRAKE_MODE-VAL
          WHEEL_BRAKE_MODE
          WHEEL_RELEASE_MODE-VAL
          WHEEL_RELEASE_MODE
          GO_TO_DOCK-VAL
          GO_TO_DOCK
          DOCK_ESCAPE-VAL
          DOCK_ESCAPE
          DO_NOT_CHARGE-VAL
          DO_NOT_CHARGE
          CHARGING-VAL
          CHARGING
          CHARGE_FINISH-VAL
          CHARGE_FINISH
          FAULT_IN_CHARGE-VAL
          FAULT_IN_CHARGE
          STOP_BTN_HIT-VAL
          STOP_BTN_HIT
          SLEEP_BTN_HIT-VAL
          SLEEP_BTN_HIT
))