(cl:in-package BaseNode-msg)
(cl:export '(ULTRASONIC_BRAKE_ENABLED-VAL
          ULTRASONIC_BRAKE_ENABLED
          EMERGENCY_BUTTON_ENABLED-VAL
          EMERGENCY_BUTTON_ENABLED
          BUMPER_BRAKE_ENABLED-VAL
          BUMPER_BRAKE_ENABLED
          AUTO_DOCK_ENABLED-VAL
          AUTO_DOCK_ENABLED
          WHEEL_RELEASE_ENABLED-VAL
          WHEEL_RELEASE_ENABLED
          WHEEL_BRAKE_ENABLED-VAL
          WHEEL_BRAKE_ENABLED
          IR_ENABLED-VAL
          IR_ENABLED
          SONIC_DISTANCE-VAL
          SONIC_DISTANCE
))