(cl:in-package BaseNode-msg)
(cl:export '(CURRENT_CONTROLLER-VAL
          CURRENT_CONTROLLER
          CURRENT_ACTION-VAL
          CURRENT_ACTION
          CURRENT_CONTROLLER_PRIORITY-VAL
          CURRENT_CONTROLLER_PRIORITY
          CURRENT_ACTION_PRIORITY-VAL
          CURRENT_ACTION_PRIORITY
))