(cl:in-package BaseNode-msg)
(cl:export '(LEFT_CONTROL_VALUE-VAL
          LEFT_CONTROL_VALUE
          LEFT_ERROR_VALUE-VAL
          LEFT_ERROR_VALUE
          LEFT_REFERENCE_SPEED_VALUE-VAL
          LEFT_REFERENCE_SPEED_VALUE
          LEFT_REAL_SPEED_VALUE-VAL
          LEFT_REAL_SPEED_VALUE
          LEFT_OUTPUT_PWM_VALUE-VAL
          LEFT_OUTPUT_PWM_VALUE
          LEFT_BRAKE_VALUE-VAL
          LEFT_BRAKE_VALUE
          RIGHT_CONTROL_VALUE-VAL
          RIGHT_CONTROL_VALUE
          RIGHT_ERROR_VALUE-VAL
          RIGHT_ERROR_VALUE
          RIGHT_REFERENCE_SPEED_VALUE-VAL
          RIGHT_REFERENCE_SPEED_VALUE
          RIGHT_REAL_SPEED_VALUE-VAL
          RIGHT_REAL_SPEED_VALUE
          RIGHT_OUTPUT_PWM_VALUE-VAL
          RIGHT_OUTPUT_PWM_VALUE
          RIGHT_BRAKE_VALUE-VAL
          RIGHT_BRAKE_VALUE
))