// Generated by gencpp from file auto_charge_service/aurco_info.msg
// DO NOT EDIT!


#ifndef AUTO_CHARGE_SERVICE_MESSAGE_AURCO_INFO_H
#define AUTO_CHARGE_SERVICE_MESSAGE_AURCO_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_charge_service
{
template <class ContainerAllocator>
struct aurco_info_
{
  typedef aurco_info_<ContainerAllocator> Type;

  aurco_info_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , get_aruco(false)
    , not_get_aruco(false)  {
    }
  aurco_info_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , get_aruco(false)
    , not_get_aruco(false)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef uint8_t _get_aruco_type;
  _get_aruco_type get_aruco;

   typedef uint8_t _not_get_aruco_type;
  _not_get_aruco_type not_get_aruco;





  typedef boost::shared_ptr< ::auto_charge_service::aurco_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_charge_service::aurco_info_<ContainerAllocator> const> ConstPtr;

}; // struct aurco_info_

typedef ::auto_charge_service::aurco_info_<std::allocator<void> > aurco_info;

typedef boost::shared_ptr< ::auto_charge_service::aurco_info > aurco_infoPtr;
typedef boost::shared_ptr< ::auto_charge_service::aurco_info const> aurco_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_charge_service::aurco_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_charge_service::aurco_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_charge_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'auto_charge_service': ['/home/c01/naya_navigation/src/auto_charge_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_charge_service::aurco_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_charge_service::aurco_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_charge_service::aurco_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_charge_service::aurco_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_charge_service::aurco_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_charge_service::aurco_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_charge_service::aurco_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e734168b30b8d8c8907e55348fd895a";
  }

  static const char* value(const ::auto_charge_service::aurco_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e734168b30b8d8cULL;
  static const uint64_t static_value2 = 0x8907e55348fd895aULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_charge_service::aurco_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_charge_service/aurco_info";
  }

  static const char* value(const ::auto_charge_service::aurco_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_charge_service::aurco_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
\n\
bool get_aruco\n\
bool not_get_aruco\n\
";
  }

  static const char* value(const ::auto_charge_service::aurco_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_charge_service::aurco_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.get_aruco);
      stream.next(m.not_get_aruco);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct aurco_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_charge_service::aurco_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_charge_service::aurco_info_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "get_aruco: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_aruco);
    s << indent << "not_get_aruco: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.not_get_aruco);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_CHARGE_SERVICE_MESSAGE_AURCO_INFO_H
