// Generated by gencpp from file auto_charge_service/auto_charge_srvResponse.msg
// DO NOT EDIT!


#ifndef AUTO_CHARGE_SERVICE_MESSAGE_AUTO_CHARGE_SRVRESPONSE_H
#define AUTO_CHARGE_SERVICE_MESSAGE_AUTO_CHARGE_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_charge_service
{
template <class ContainerAllocator>
struct auto_charge_srvResponse_
{
  typedef auto_charge_srvResponse_<ContainerAllocator> Type;

  auto_charge_srvResponse_()
    : goal_x(0.0)
    , goal_y(0.0)  {
    }
  auto_charge_srvResponse_(const ContainerAllocator& _alloc)
    : goal_x(0.0)
    , goal_y(0.0)  {
  (void)_alloc;
    }



   typedef double _goal_x_type;
  _goal_x_type goal_x;

   typedef double _goal_y_type;
  _goal_y_type goal_y;





  typedef boost::shared_ptr< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct auto_charge_srvResponse_

typedef ::auto_charge_service::auto_charge_srvResponse_<std::allocator<void> > auto_charge_srvResponse;

typedef boost::shared_ptr< ::auto_charge_service::auto_charge_srvResponse > auto_charge_srvResponsePtr;
typedef boost::shared_ptr< ::auto_charge_service::auto_charge_srvResponse const> auto_charge_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_charge_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'auto_charge_service': ['/home/c01/naya_navigation/src/auto_charge_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13b965790a69b58a06825eaf607cdbe7";
  }

  static const char* value(const ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13b965790a69b58aULL;
  static const uint64_t static_value2 = 0x06825eaf607cdbe7ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_charge_service/auto_charge_srvResponse";
  }

  static const char* value(const ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 goal_x\n\
float64 goal_y\n\
";
  }

  static const char* value(const ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_x);
      stream.next(m.goal_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct auto_charge_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_charge_service::auto_charge_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal_x: ";
    Printer<double>::stream(s, indent + "  ", v.goal_x);
    s << indent << "goal_y: ";
    Printer<double>::stream(s, indent + "  ", v.goal_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_CHARGE_SERVICE_MESSAGE_AUTO_CHARGE_SRVRESPONSE_H
