// Generated by gencpp from file auto_charge_service/auto_charge_srv.msg
// DO NOT EDIT!


#ifndef AUTO_CHARGE_SERVICE_MESSAGE_AUTO_CHARGE_SRV_H
#define AUTO_CHARGE_SERVICE_MESSAGE_AUTO_CHARGE_SRV_H

#include <ros/service_traits.h>


#include <auto_charge_service/auto_charge_srvRequest.h>
#include <auto_charge_service/auto_charge_srvResponse.h>


namespace auto_charge_service
{

struct auto_charge_srv
{

typedef auto_charge_srvRequest Request;
typedef auto_charge_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct auto_charge_srv
} // namespace auto_charge_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_charge_service::auto_charge_srv > {
  static const char* value()
  {
    return "1fb8fd8311cc5d196025d0fcca8c666b";
  }

  static const char* value(const ::auto_charge_service::auto_charge_srv&) { return value(); }
};

template<>
struct DataType< ::auto_charge_service::auto_charge_srv > {
  static const char* value()
  {
    return "auto_charge_service/auto_charge_srv";
  }

  static const char* value(const ::auto_charge_service::auto_charge_srv&) { return value(); }
};


// service_traits::MD5Sum< ::auto_charge_service::auto_charge_srvRequest> should match 
// service_traits::MD5Sum< ::auto_charge_service::auto_charge_srv > 
template<>
struct MD5Sum< ::auto_charge_service::auto_charge_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_charge_service::auto_charge_srv >::value();
  }
  static const char* value(const ::auto_charge_service::auto_charge_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_charge_service::auto_charge_srvRequest> should match 
// service_traits::DataType< ::auto_charge_service::auto_charge_srv > 
template<>
struct DataType< ::auto_charge_service::auto_charge_srvRequest>
{
  static const char* value()
  {
    return DataType< ::auto_charge_service::auto_charge_srv >::value();
  }
  static const char* value(const ::auto_charge_service::auto_charge_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_charge_service::auto_charge_srvResponse> should match 
// service_traits::MD5Sum< ::auto_charge_service::auto_charge_srv > 
template<>
struct MD5Sum< ::auto_charge_service::auto_charge_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_charge_service::auto_charge_srv >::value();
  }
  static const char* value(const ::auto_charge_service::auto_charge_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_charge_service::auto_charge_srvResponse> should match 
// service_traits::DataType< ::auto_charge_service::auto_charge_srv > 
template<>
struct DataType< ::auto_charge_service::auto_charge_srvResponse>
{
  static const char* value()
  {
    return DataType< ::auto_charge_service::auto_charge_srv >::value();
  }
  static const char* value(const ::auto_charge_service::auto_charge_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_CHARGE_SERVICE_MESSAGE_AUTO_CHARGE_SRV_H
